# Generated by Django 3.2.9 on 2022-01-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_confirmed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
