# Generated by Django 3.2.9 on 2022-01-06 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_choice_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='timespent',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
