# Generated by Django 3.2.9 on 2022-01-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_choice_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_confirmed',
        ),
    ]
