# Generated by Django 3.2.9 on 2022-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_question_choice_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='timespent',
            field=models.DurationField(),
        ),
    ]
