# Generated by Django 3.2.9 on 2022-01-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_choice_timespent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='timespent',
        ),
        migrations.AddField(
            model_name='choice',
            name='timespent_h',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='timespent_m',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='timespent_s',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
