# Generated by Django 3.2.9 on 2022-01-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220107_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='repeat_quiz',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
