# Generated by Django 3.2.9 on 2022-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220111_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_questuion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
