# Generated by Django 3.2.9 on 2022-01-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_answer_correct_questuion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct_questuion',
            new_name='correct_question',
        ),
    ]
