# Generated by Django 3.2.9 on 2022-01-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_choicearchive_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicearchive',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.answer'),
        ),
        migrations.AlterField(
            model_name='choicearchive',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_related', to='main.question'),
        ),
    ]
